spring.application.name=order-tracking-analytics


# What this does: Connects your app to CloudAMQP and sets up H2 database.
server.port=8080
spring.rabbitmq.addresses=amqps://gtpmlmcb:vRm0y0mkf2UB1vwFPRkgff9PmPhaN4te@puffin.rmq2.cloudamqp.com/gtpmlmcb
spring.rabbitmq.username=gtpmlmcb
spring.rabbitmq.password=vRm0y0mkf2UB1vwFPRkgff9PmPhaN4te

# H2 Database
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.jpa.show-sql=true

# Logging
logging.level.com.example.ordertracking=DEBUG
logging.level.org.springframework.amqp=DEBUG
logging.level.root=ERROR


# Disable Docker Compose
spring.docker.compose.enabled=false

